# Generated by Django 6.0.5 on 2026-06-13 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Date_added',
        ),
    ]
